### ISSUE TITLE
[BUG] PSBrush ignores color

### ISSUE THREAD

**Issue by IcyTv** [arch-inc/fabricjs-psbrush#12]
Heyho,

So as the title says, the PSBrush ignores color. Meaning, it draws with the set color, but the PSStrokes rendered on the canvas are always black. 

From my investigation, I think this might be down to PSStrokes not having any concepts of color, but I might be wrong here

**Comment by IcyTv** [comment]
Okay, so I found the solution: You are missing the line to `ctx.strokeStyle = this.stroke;` in the `_renderStroke` function of `PSStroke`.

**Comment by arcatdmz** [comment]
@IcyTv Thank you for your bug report, and even the PR to fix it! Let me quickly review and accept it.

**Comment by arcatdmz** [comment]
I've confirmed that the PR works perfectly, so merged it and published v0.0.16 on npm. Thank you again for your contribution 🎉
