### ISSUE TITLE
Pixellate when changing brush width between two strokes

### ISSUE THREAD

**Issue by oz-** [arch-inc/fabricjs-psbrush#15]
Hi and thank you for this great work!

I have an issue when changing the brush width between two strokes.
Everything is fine when we are on small values, but when I set the width to higher values I have a very pixellated and cropped result when finalizing (see below). 

<img width="807" alt="fabricjs-psbrush" src="https://user-images.githubusercontent.com/1618148/116084975-a0ef1a00-a69e-11eb-9c9a-2f27d5045087.png">

During the stroke everything is OK, and if I initialize the brush with high value also.

Any idea on how to avoid this behavior?
Thank you!

### **EDIT**

It seems to be a fabric.js problem
See https://github.com/fabricjs/fabric.js/issues/4672

**Comment by oz-** [comment]
Well the solution was in the issue mentioned above: fabric.js accepts string in place of number but produces this strange behavior.

**Comment by arcatdmz** [comment]
@oz- Thanks for the issue report -- we weren't aware of this Fabric.js issue. Good luck with your app development!
