### ISSUE TITLE
Not getting psbrush to work on iPad

### ISSUE THREAD

**Issue by sjscotti** [arch-inc/fabricjs-psbrush#4]
Hi
I had incorporated psbrush into my graphics application and found that it didn't work on the iPad.  So I tested the demo site at https://arch-inc.github.io/fabricjs-psbrush/ on the iPad and found the same issue.  I am just using my finger to draw.  A very fine line is drawn on the screen - much finer than the line drawn on my Windows laptop - and there is no pressure effect.  Though the demo site says it worked with iPad Pro, it is not working on my (actually my wife's) iPad.  Her OS is iPadOS 13.5.1 which is up to date, and her iPad model is iPad Air (3rd generation, model MUUJ2LL/A).  However, it is working fine on my iPhone 7 Plus with iOS 13.5.1 using finger input including the pressure effect.   Otherwise it is working great on other platforms I've tried!

**Comment by arcatdmz** [comment]
@sjscotti Thank you for the feedback!

Finger press does not provide any pressure information on iPad OS, to my understanding. Therefore, this library currently requires the use of an iPad pencil.

**Comment by sjscotti** [comment]
OK, thanks!  Having it work on iPhone but not
the iPad was unexpected.  I’ll close out the issue.
